### ISSUE TITLE
Action doesn't find YAML files

### ISSUE THREAD

**Issue by JohnnyJayJay** [GrantBirki/json-yaml-validate#20]
I have a [workflow config](https://github.com/codosseum-org/challenges/blob/main/.github/workflows/validate.yml) using this action.

I created a [Pull Request](https://github.com/codosseum-org/challenges/pull/1) to the main branch in this repo, triggering the validation job. I added a file that should be validated by the job, but [it wasn't](https://github.com/codosseum-org/challenges/actions/runs/5808878189/job/15746565470?pr=1). The action didn't find any yaml files in `challenges/`. From a quick look at the action's code, I could not figure out what's wrong. Any idea?

**Comment by GrantBirki** [comment]
👋 Hey @JohnnyJayJay! I have made several improvements / changes to this project since `v1.5.0` (which I see you are using).

Would you be able to upgrade to the latest version of this Action and re-run your changes with "debug" mode. You can put a link to the debug output here, and I'll try and take a look to see what is going on.

Most importantly, I merged a pull request today (https://github.com/GrantBirki/json-yaml-validate/pull/25) that should greatly improve the debug results from this Action for trouble shooting 😄 

**Actions Debug Example**:

<img width="1233" alt="Screenshot 2023-08-10 at 11 34 17 AM" src="https://github.com/GrantBirki/json-yaml-validate/assets/23362539/042d86b5-52e7-433a-b38b-e0139c4fb687">

**Comment by JohnnyJayJay** [comment]
Oh, sorry, copied the definition from somewhere else and didn't pay attention to the version.

The issue [still occurs](https://github.com/codosseum-org/challenges/actions/runs/5820172758/job/15780030332?pr=1) on the latest version (2.1.0). But it seems like the debug output shows us the culprit:

```
##[debug]using baseDir: challenges
##[debug]using glob: **/*.{yaml,yml}
##[debug]found file: challenges/rotating-numbers/challenge.yml
##[debug]skipping yaml since it should be treated as json: challenges/rotating-numbers/challenge.yml
🔎 no JSON files were detected
🔎 no YAML files were detected
```

**Comment by GrantBirki** [comment]
```
skipping yaml since it should be treated as json: challenges/rotating-numbers/challenge.yml
```

hmmm but then why isn't it being detected by the JSON validator? It makes sense that it should be skipped by the yaml processor but it shouldn't be skipped by the JSON one

**Comment by GrantBirki** [comment]
I think I found the issue! If you look at [these lines](https://github.com/GrantBirki/json-yaml-validate/blob/9dae423bea2ed93a0cc7b00afd7d4786ba6d3799/src/functions/json-validator.js#L70-L77) you can see that we are only looking for `.yaml` file extensions in this case, and not `.yml` which is what you are using. This looks like a bug as we should be checking for both

**Comment by GrantBirki** [comment]
Now... this looks like the bug to me -> [link](https://github.com/codosseum-org/challenges/actions/runs/5820172758/job/15780030332?pr=1#step:3:37)

That glob looks botched due to the whitespace near `yml` which would prevent your file from being parsed

**Comment by GrantBirki** [comment]
@JohnnyJayJay Would you be able to use `GrantBirki@json-as-yaml-fix` in your Action workflow to see if that resolves the issue? 

> You can temp point your Action to a branch (instead of a tag) and this will let us test the bug at hand

**Comment by JohnnyJayJay** [comment]
See workflow details - it's not read as YAML now.

**Comment by JohnnyJayJay** [comment]
BTW, there is  another inconsistency - the YAML extensions are stripped of the leading `.`, while the JSON extension is not. This certainly doesn't cause my issue but it will cause a file like `script-yaml` (no extension) to be validated even though it probably shouldn't be

**Comment by GrantBirki** [comment]
@JohnnyJayJay I pushed a few commits to that branch. Would you mind testing again? I think it _should_ work now

**Comment by JohnnyJayJay** [comment]
It worked but it seems to stop the validation after the first failure, such that you don't see all errors. In the [last run](https://github.com/codosseum-org/challenges/actions/runs/5822714222/job/15787959106?pr=1) for example, there should be two errors because two required fields are missing. But it's just reporting one. Is this intended behaviour? I have nothing to compare to.

**Comment by JohnnyJayJay** [comment]
> I don't think it actually stopped the validation, but rather you only have one `.yml` file that is in the directory for it to check. So one it completed checks on that file, all the work for the Action to do was complete! Try adding another file to that directory that you know will pass the validation and see if it detects both to be sure. I think this is working as expected now

No, I mean there are 2 errors in that one file.

**Comment by GrantBirki** [comment]
> No, I mean there are 2 errors in that one file.

@JohnnyJayJay ah that is absolutely a bug then! Do I have permission to use your file and commit it to my repo and use it as a unit test? This will allow me to test this bug and use your file as a living unit test that is a real world example. 🙇

**Comment by JohnnyJayJay** [comment]
> > No, I mean there are 2 errors in that one file.
> 
> @JohnnyJayJay ah that is absolutely a bug then! Ideally, all errors should be reported and processing shouldn't just stop at the first error seen in the file.
> 
> Do I have permission to use your file and commit it to my repo and use it as a unit test? This will allow me to test this bug and use your file as a living unit test that is a real world example. 🙇 

Sure, though the errors are pretty benign (two keys are erroneously given in snake_case instead of camelCase).

The challenge-schema.json uses Apache 2.0 as its license, the challenge.yml CC BY-SA 4.0.

**Comment by GrantBirki** [comment]
I'm opening a new issue to track this new bug
